export type MatchMode = "includes" | "exact" | "startsWith";
export type SurfaceStyle = "glass" | "neon" | "minimal";
export type TicketStatus = "pending" | "paid" | "processing" | "completed" | "cancelled" | "closed";
export type AutoReplyRule = {
    id: string;
    enabled: boolean;
    trigger: string;
    response: string;
    matchMode: MatchMode;
    ignoreCase: boolean;
    cooldownSeconds: number;
};
export type ReviewSettings = {
    enabled: boolean;
    channelId: string;
    panelTitle: string;
    panelDescription: string;
    accentColor: string;
    thankYouMessage: string;
};
export type TicketCategory = {
    id: string;
    label: string;
    emoji: string;
};
export type ProductItem = {
    id: string;
    name: string;
    category: string;
    priceLabel: string;
    description?: string;
    imageUrl?: string;
    featured?: boolean;
    enabled: boolean;
};
export type BlacklistEntry = {
    id: string;
    userId: string;
    note: string;
};
export type BalanceRecord = {
    userId: string;
    username: string;
    balance: number;
    totalSpent: number;
    note: string;
    updatedAt: string;
};
export type DashboardAccountRole = "admin" | "developer" | "owner";
export type DashboardAccount = {
    id: string;
    username: string;
    password: string;
    role: DashboardAccountRole;
    enabled: boolean;
    displayName?: string;
    authMode?: "local" | "discord" | "both";
    discordUserId?: string;
    allowedGuildIds?: string[];
};
export type CustomerAccountProvider = "local" | "google";
export type CustomerAccountRole = "customer";
export type CustomerAccount = {
    id: string;
    username: string;
    password: string;
    displayName: string;
    email: string;
    phone: string;
    provider: CustomerAccountProvider;
    role: CustomerAccountRole;
    enabled: boolean;
    emailVerified: boolean;
    phoneVerified: boolean;
    emailVerificationCode?: string;
    emailVerificationExpiresAt?: string;
    phoneVerificationCode?: string;
    phoneVerificationExpiresAt?: string;
    createdAt: string;
};
export type PaymentMethodConfig = {
    id: string;
    label: string;
    instructions: string;
    accountInfo: string;
    enabled: boolean;
};
export type StorefrontSettings = {
    enabled: boolean;
    heroTitle: string;
    heroDescription: string;
    supportGoogleLogin: boolean;
    googleLoginConfigured: boolean;
    googleClientId?: string;
    googleRedirectUrl?: string;
    notificationChannelId: string;
    productAnnouncementGuildId: string;
    productAnnouncementChannelId: string;
    paymentMethods: PaymentMethodConfig[];
};
export type StoreOrderStatus = "pending_payment" | "payment_code_ready" | "paid" | "processing" | "completed" | "cancelled";
export type StoreOrderItem = {
    productId: string;
    name: string;
    category: string;
    quantity: number;
    priceLabel: string;
    unitPrice: number;
    subtotal: number;
};
export type StoreOrderMessage = {
    id: string;
    senderType: "customer" | "staff" | "system";
    senderName: string;
    message: string;
    createdAt: string;
};
export type StoreOrderRecord = {
    id: string;
    customerId: string;
    customerUsername: string;
    customerDisplayName: string;
    ticketId?: string;
    ticketChannelId?: string;
    items: StoreOrderItem[];
    paymentMethodId: string;
    paymentMethodLabel: string;
    totalAmount: number;
    deliveryAccount: string;
    contact: string;
    note: string;
    status: StoreOrderStatus;
    messages: StoreOrderMessage[];
    opayMerchantTradeNo?: string;
    opayTradeNo?: string;
    opayPaymentCode?: string;
    opayExpireAt?: string;
    createdAt: string;
    updatedAt: string;
};
export type PartnershipApplicationStatus = "pending" | "approved" | "rejected";
export type PartnershipServer = {
    id: string;
    serverName: string;
    description: string;
    inviteUrl: string;
    bannerUrl: string;
    contact: string;
    tags: string[];
    mutualPromotion: boolean;
    featured: boolean;
    enabled: boolean;
    sourceApplicationId?: string;
    createdAt: string;
    updatedAt: string;
};
export type PartnershipApplication = {
    id: string;
    serverName: string;
    ownerName: string;
    ownerUserId: string;
    contact: string;
    inviteUrl: string;
    description: string;
    benefits: string;
    reviewNote: string;
    status: PartnershipApplicationStatus;
    createdAt: string;
    updatedAt: string;
    processedAt?: string;
};
export type PassOrderStatus = "pending_payment" | "paid" | "queued" | "delivering" | "completed" | "cancelled" | "refunded";
export type PassOrderRecord = {
    id: string;
    userId: string;
    username: string;
    guildId: string;
    ticketId?: string;
    channelId?: string;
    productId: string;
    productName: string;
    category: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
    robloxUserId: string;
    robloxUsername: string;
    paymentMethod: string;
    note: string;
    status: PassOrderStatus;
    createdAt: string;
    updatedAt: string;
    paidAt?: string;
    queuedAt?: string;
    deliveredAt?: string;
    fulfilledBy?: string;
};
export type ChannelOverwriteSnapshot = {
    id: string;
    type: "role" | "member";
    allow: string;
    deny: string;
};
export type CategorySnapshot = {
    name: string;
    position: number;
    overwrites: ChannelOverwriteSnapshot[];
};
export type ServerChannelSnapshot = {
    name: string;
    type: "text" | "voice" | "announcement";
    position: number;
    parentName?: string;
    topic?: string;
    nsfw?: boolean;
    rateLimitPerUser?: number;
    bitrate?: number;
    userLimit?: number;
    overwrites: ChannelOverwriteSnapshot[];
    messages?: ChannelMessageSnapshot[];
};
export type ChannelMessageSnapshot = {
    authorTag: string;
    content: string;
    createdAt: string;
};
export type ServerStructureBackup = {
    guildId: string;
    guildName: string;
    createdAt: string;
    categories: CategorySnapshot[];
    channels: ServerChannelSnapshot[];
};
export type TicketSettings = {
    enabled: boolean;
    categoryId: string;
    paidCategoryId: string;
    supportRoleId: string;
    autoRoleId: string;
    logChannelId: string;
    transcriptChannelId: string;
    allowDashboardClose: boolean;
    completedCountChannelId: string;
    completedCountLabel: string;
    panelTitle: string;
    panelDescription: string;
    buttonLabel: string;
    buttonEmoji: string;
    maxOpenTicketsPerUser: number;
    categories: TicketCategory[];
    products: ProductItem[];
    blacklist: BlacklistEntry[];
};
export type BrandSettings = {
    serverName: string;
    tagline: string;
    primaryColor: string;
    secondaryColor: string;
    surfaceStyle: SurfaceStyle;
};
export type ModerationSettings = {
    antiSpamEnabled: boolean;
    spamMessageLimit: number;
    spamWindowSeconds: number;
    timeoutMinutes: number;
    logChannelId: string;
};
export type LinkedGuildConfig = {
    guildId: string;
    label: string;
    enabled: boolean;
    reviewChannelId: string;
    ticketCategoryId: string;
    paidTicketCategoryId: string;
    supportRoleId: string;
    autoRoleId: string;
    ticketLogChannelId: string;
    transcriptChannelId: string;
    completedCountChannelId: string;
    completedCountLabel: string;
    moderationLogChannelId: string;
    productAnnouncementChannelId: string;
};
export type GuildSettings = {
    guildId: string;
    linkedGuilds: LinkedGuildConfig[];
    adminKey: string;
    accounts: DashboardAccount[];
    storefront: StorefrontSettings;
    brand: BrandSettings;
    moderation: ModerationSettings;
    review: ReviewSettings;
    ticket: TicketSettings;
    autoReplies: AutoReplyRule[];
    faq: Array<{
        id: string;
        question: string;
        answer: string;
    }>;
};
export type ReviewRecord = {
    id: string;
    guildId: string;
    userId: string;
    username: string;
    avatarUrl?: string;
    stars: number;
    content: string;
    createdAt: string;
};
export type GiveawayRecord = {
    id: string;
    guildId: string;
    channelId: string;
    messageId: string;
    prize: string;
    winnersCount: number;
    endAt: string;
    participants: string[];
    ended: boolean;
    winnerIds: string[];
    createdBy: string;
};
export type TicketRecord = {
    id: string;
    guildId: string;
    channelId: string;
    publicPanelMessageId?: string;
    adminPanelMessageId?: string;
    userId: string;
    username: string;
    categoryId: string;
    categoryLabel: string;
    reason: string;
    productId?: string;
    productName?: string;
    quantity?: number;
    totalAmount?: number;
    paymentMethod?: string;
    cvsSubPayment?: "CVS" | "FAMILY" | "IBON" | "OKMART" | "HILIFE";
    quickOpayOrderId?: string;
    opayPaymentCode?: string;
    opayExpireAt?: string;
    claimedBy?: string;
    status: TicketStatus;
    createdAt: string;
    closedAt?: string;
    completedAt?: string;
};
export type DashboardStats = {
    totalReviews: number;
    averageRating: number;
    openTickets: number;
    completedTickets: number;
    autoReplyRules: number;
    blacklistedUsers: number;
    balanceUsers: number;
    totalStoredBalance: number;
    storefrontTotalOrders: number;
    storefrontPendingOrders: number;
    storefrontPaidOrders: number;
    storefrontRevenue: number;
    storefrontTodayRevenue: number;
    storefrontWeekRevenue: number;
    storefrontMonthRevenue: number;
    storefrontTodayOrders: number;
    storefrontWeekOrders: number;
    storefrontMonthOrders: number;
};
export declare const defaultGuildSettings: (guildId: string, adminKey: string) => GuildSettings;
